[package]
name = "switcheroo"
version = "0.2.0"
edition = "2021"
authors = [ "Ethan Budd <budde25@protonmail.com>" ]
description = "A CLI and GUI for the Nintendo Switch RCM exploit"
keywords = [ "CLI", "utilities" ]
categories = [ "command-line-utilities" ]
readme = "README.md"
license = "GPL-2.0-or-later"

[dependencies]
clap = { version = "3.2.8", features = [ "derive" ] }
color-eyre = "0.6.1"
dirs = "4.0.0"
eframe = { version = "0.18.0", features = [ "dark-light" ], optional = true }
egui_extras = { version = "0.18.0", features = [ "svg" ], optional = true }
image = "0.24.2"
native-dialog = { version = "0.6.3", optional = true }
tegra-rcm = { version = "0.3.0", path = "crates/tegra-rcm" }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.14", features = [ "env-filter" ] }

[build-dependencies]
clap = { version = "3.2.8", features = [ "derive" ] }
clap_complete = "3.2.3"

[features]
default = [ "gui" ]
gui = [ "dep:egui_extras", "dep:eframe", "dep:native-dialog" ]

[workspace]
members = [ "crates/tegra-rcm" ]

[profile.release]
strip = "symbols"

[package.metadata.deb]
depends = "$auto"
section = "utility"
assets = [
    [ "target/release/switcheroo", "usr/bin/", "755" ],
    [ "LICENSE", "usr/share/doc/switcheroo/", "644" ],
    [ "README.md", "usr/share/doc/switcheroo/README", "644" ],
    # shell completions
    [ "extra/completions/switcheroo.bash", "usr/share/bash-completion/completions/switcheroo", "644" ],
    [ "extra/completions/switcheroo.fish", "usr/share/fish/vendor_completions.d/switcheroo.fish", "644" ],
    [ "extra/completions/_switcheroo", "usr/share/zsh/vendor-completions/_switcheroo", "644" ],
    # desktop file
    [ "extra/linux/io.ebudd.Switcheroo.desktop", "usr/share/applications/", "644" ],
    # icon
    [ "extra/logo/io.ebudd.Switcheroo.png", "/usr/share/icons/hicolor/512x512/apps/", "644" ],
    # meta info
    [ "extra/linux/io.ebudd.Switcheroo.appdata.xml", "/usr/share/metainfo/", "644" ],
    # udev rules
    [ "extra/linux/99-switch.rules", "/lib/udev/rules.d/", "644" ],
]
