[package]
name = "switcheroo"
version = "0.1.0"
edition = "2021"
authors = ["Ethan Budd <budde25@protonmail.com>"]
description = "A CLI and GUI for the Nintendo Switch RCM exploit"
keywords = ["CLI", "utilities"]
categories = ["command-line-utilities"]
readme = "README.md"
license = "GPL-2.0-or-later"


[dependencies]
clap = { version = "3.1.15", features = ["derive"] }
color-eyre = "0.6.1"

egui = "0.18.1"
eframe = "0.18.0"
rfd = "0.8.2"
# image = "0.24.2"

rcm-lib = { version = "0.1.0", path = "crates/rcm-lib" }

[build-dependencies]
clap_complete = "3.1.3"
clap = { version = "3.1.15", features = ["derive"] }

[workspace]
members = ["crates/rcm-lib"]
