[package]
name = "switcheroo"
version = "0.1.0"
edition = "2021"
authors = ["Ethan Budd <budde25@protonmail.com>"]
description = "A CLI and GUI for the Nintendo Switch RCM exploit"
keywords = ["CLI", "utilities"]
categories = ["command-line-utilities"]
readme = "README.md"
license = "GPL-2.0-or-later"


[dependencies]
clap = { version = "3.1.17", features = ["derive"] }
color-eyre = "0.6.1"

# gui only
egui = { version = "0.18.1", optional = true }
egui_extras = { version = "0.18.0", features = ["svg"], optional = true }
eframe = { version = "0.18.0", features = ["dark-light"], optional = true }
rfd = { version = "0.8.2", optional = true }

tegra-rcm = { version = "0.1.0", path = "crates/tegra-rcm" }
rusb = { version = "0.9.1" }

[build-dependencies]
clap_complete = "3.1.4"
clap = { version = "3.1.17", features = ["derive"] }

[features]
default = ["gui"]
gui = ["dep:egui", "dep:egui_extras", "dep:eframe", "dep:rfd"]

[workspace]
members = ["crates/tegra-rcm"]

[package.metadata.deb]
depends = "$auto"
section = "utility"
assets = [
    [
        "target/release/switcheroo",
        "usr/bin/",
        "755",
    ],
    [
        "LICENSE",
        "usr/share/doc/switcheroo/LICENSE",
        "644",
    ],
    [
        "README.md",
        "usr/share/doc/switcheroo/README",
        "644",
    ],

    [
        "extra/completions/switcheroo.bash",
        "usr/share/bash-completion/completions/switcheroo",
        "644",
    ],
    [
        "extra/completions/switcheroo.fish",
        "usr/share/fish/vendor_completions.d/switcheroo.fish",
        "644",
    ],
    [
        "extra/completions/_switcheroo",
        "usr/share/zsh/vendor-completions/_switcheroo",
        "644",
    ],
    # desktop file
    [
        "extra/linux/io.ebudd.Switcheroo.desktop",
        "usr/share/applications/io.ebudd.Switcheroo.desktop",
        "644",
    ],
    # icon
    [
        "extra/logo/io.ebudd.Switcheroo.png",
        "/usr/share/icons/hicolor/512x512/apps/io.ebudd.Swithcheroo.png",
        "644",
    ],
    # meta info
    [
        "extra/linux/io.ebudd.Switcheroo.appdata.xml",
        "/usr/share/metainfo/io.ebudd.Switcheroo.appdata.xml",
        "644",
    ],
]

[package.metadata.rpm]
package = "switcheroo"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
switcheroo = { path = "/usr/bin/switcheroo" }
