[package]
name = "switcheroo"
version = "0.1.0"
edition = "2021"
authors = ["Ethan Budd <budde25@protonmail.com>"]
description = "A CLI and GUI for the Nintendo Switch RCM exploit"
keywords = ["CLI", "utilities"]
categories = ["command-line-utilities"]
readme = "README.md"
license = "GPL-2.0-or-later"


[dependencies]
clap = { version = "3.1.15", features = ["derive"] }
color-eyre = "0.6.1"

# gui only
egui = { version = "0.18.1", optional = true }
egui_extras = { version = "0.18.0", features = ["svg"], optional = true }
eframe = { version = "0.18.0", features = ["dark-light"], optional = true }
rfd = { version = "0.8.2", optional = true }

tegra-rcm = { version = "0.1.0", path = "crates/tegra-rcm" }

[build-dependencies]
clap_complete = "3.1.3"
clap = { version = "3.1.15", features = ["derive"] }

[features]
default = ["gui"]
gui = ["dep:egui", "dep:egui_extras", "dep:eframe", "dep:rfd"]

[workspace]
members = ["crates/tegra-rcm"]

[package.metadata.deb]
depends = "$auto"
section = "utility"
assets = [
    [
        "target/release/switcheroo",
        "usr/bin/",
        "755",
    ],
    [
        "LICENSE",
        "usr/share/doc/switcheroo/LICENSE",
        "644",
    ],
    [
        "README.md",
        "usr/share/doc/switcheroo/README",
        "644",
    ],

    # TODO: generate automatically
    [
        "extra/completions/switcheroo.bash",
        "usr/share/bash-completion/completions/switcheroo",
        "644",
    ],
    [
        "extra/completions/switcheroo.fish",
        "usr/share/fish/vendor_completions.d/switcheroo.fish",
        "644",
    ],
    [
        "extra/completions/_switcheroo",
        "usr/share/zsh/vendor-completions/",
        "644",
    ],
]
