[package]
name = "switcheroo"
version = "0.1.0"
edition = "2021"
authors = ["Ethan Budd <budde25@protonmail.com>"]
description = "A command line interface for switch RCM"
keywords = ["CLI", "utilities"]
categories = ["command-line-utilities"]
readme = "README.md"


[dependencies]
clap = { version = "3.1.14", features = ["derive"] }
color-eyre = "0.6.1"
rcm-lib = { path = "crates/rcm-lib" }

[workspace]
members = ["crates/rcm-lib"]
