[package]
name = "rcm-hax"
version = "0.1.0"
edition = "2021"
authors = ["Ethan Budd <budde25@protonmail.com>"]
description = "A command line interface for switch RCM"
keywords = ["CLI", "utilities"]
categories = ["command-line-utilities"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.12", features = ["derive"] }
color-eyre = "0.6.1"
rcm-lib = { path = "crates/rcm-lib" }

[workspace]
members = ["crates/rcm-lib"]
