[package]
name = "tegra-rcm"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"
authors = ["Ethan Budd <budde25@protonmail.com>"]
description = "A library to help exploit the bootROM exploit for the Tegra X1's RCM mode"
repository = "https://github.com/budde25/switcheroo/tree/main/crates/tegra-rcm"
readme = "README.md"
categories = ["os"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.1"
thiserror = "1.0.31"

[target.'cfg(target_os = "linux")'.dependencies]
glob = "0.3.0"
nix = "0.24.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
