name: CD

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  macos:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as it uses the current rustc version as its cache key
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin
      - name: Test
        run: cargo test --release
      - name: Build ARM
        run: cargo build --release --target=aarch64-apple-darwin
      - name: Make DMG
        run: |
          make dmg-universal
          mv target/release/osx/Switcheroo.dmg switcheroo-${{ github.ref_name }}_universal.dmg
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            switcheroo*.dmg

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as it uses the current rustc version as its cache key
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libssl-dev rpm
      - name: Install cargo deb
        run: cargo install cargo-deb
      - name: Create .deb package
        run: |
          cargo deb --output switcheroo.deb
          mv switcheroo.deb switcheroo-${{ github.ref_name }}_amd64.deb
      - name: Install cargo rpm
        run: cargo install cargo-rpm
      - name: Create .rpm package
        run: |
          cargo rpm build
          mv target/release/rpmbuild/RPMS/x86_64/switcheroo*.rpm switcheroo-${{ github.ref_name }}_amd64.rpm
      - name: Install AppImage dependencies
        run: |
          wget https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.0.0/appimage-builder-1.0.0-d3ce41f-x86_64.AppImage
          chmod +x *.AppImage
          sudo mv *.AppImage /usr/bin/appimage-builder
          wget https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage
          chmod +x *.AppImage
          sudo mv *.AppImage /usr/bin/appimagetool
      - name: Create AppImage
        run: |
          ./create_appimage.sh
          mv Switcheroo*.AppImage switcheroo-${{ github.ref_name }}_amd64.AppImage
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            switcheroo*.AppImage
            switcheroo*.deb
            switcheroo*.rpm
